"""empty message

Revision ID: 02bb6b390f80
Revises: 
Create Date: 2024-04-21 11:22:36.003185

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '02bb6b390f80'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('landlords',
    sa.Column('LandlordID', sa.Integer(), nullable=False),
    sa.Column('Name', sa.String(), nullable=True),
    sa.Column('ContactInfo', sa.String(), nullable=True),
    sa.Column('BankAcctInfo', sa.String(), nullable=True),
    sa.Column('Address', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('LandlordID')
    )
    op.create_table('tenants',
    sa.Column('TenantID', sa.Integer(), nullable=False),
    sa.Column('Name', sa.String(), nullable=True),
    sa.Column('ContactInfo', sa.String(), nullable=True),
    sa.Column('Occupation', sa.String(), nullable=True),
    sa.Column('CurrentAddr', sa.String(), nullable=True),
    sa.Column('PrevAddr', sa.String(), nullable=True),
    sa.Column('EmergencyCnt', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('TenantID')
    )
    op.create_table('properties',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('Bedrooms', sa.Integer(), nullable=True),
    sa.Column('image', sa.String(), nullable=True),
    sa.Column('Size', sa.Float(), nullable=True),
    sa.Column('RentAmount', sa.Float(), nullable=True),
    sa.Column('Status', sa.String(), nullable=True),
    sa.Column('LandlordID', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['LandlordID'], ['landlords.LandlordID'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lease_agreements',
    sa.Column('LeaseID', sa.Integer(), nullable=False),
    sa.Column('PropertyID', sa.Integer(), nullable=True),
    sa.Column('TenantID', sa.Integer(), nullable=True),
    sa.Column('StartDate', sa.Date(), nullable=True),
    sa.Column('EndDate', sa.Date(), nullable=True),
    sa.Column('RentAmount', sa.Float(), nullable=True),
    sa.Column('PaymentSchedule', sa.String(), nullable=True),
    sa.Column('DepositAmount', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['PropertyID'], ['properties.id'], ),
    sa.ForeignKeyConstraint(['TenantID'], ['tenants.TenantID'], ),
    sa.PrimaryKeyConstraint('LeaseID')
    )
    op.create_table('maintenance_requests',
    sa.Column('RequestID', sa.Integer(), nullable=False),
    sa.Column('PropertyID', sa.Integer(), nullable=True),
    sa.Column('Description', sa.String(), nullable=True),
    sa.Column('RequestDate', sa.Date(), nullable=True),
    sa.Column('RequestedBy', sa.String(), nullable=True),
    sa.Column('Status', sa.String(), nullable=True),
    sa.Column('AssignedStaff', sa.String(), nullable=True),
    sa.Column('CompletionDate', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['PropertyID'], ['properties.id'], ),
    sa.PrimaryKeyConstraint('RequestID')
    )
    op.create_table('payments',
    sa.Column('PaymentID', sa.Integer(), nullable=False),
    sa.Column('LeaseID', sa.Integer(), nullable=True),
    sa.Column('TenantID', sa.Integer(), nullable=True),
    sa.Column('PaymentDate', sa.Date(), nullable=True),
    sa.Column('PaymentAmount', sa.Float(), nullable=True),
    sa.Column('PaymentMethod', sa.String(), nullable=True),
    sa.Column('PaymentStatus', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['LeaseID'], ['lease_agreements.LeaseID'], ),
    sa.ForeignKeyConstraint(['TenantID'], ['tenants.TenantID'], ),
    sa.PrimaryKeyConstraint('PaymentID')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('payments')
    op.drop_table('maintenance_requests')
    op.drop_table('lease_agreements')
    op.drop_table('properties')
    op.drop_table('tenants')
    op.drop_table('landlords')
    # ### end Alembic commands ###
