"""empty message

Revision ID: 242124cb03d6
Revises: 7ee26f6d76e3
Create Date: 2024-04-23 09:18:02.552651

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '242124cb03d6'
down_revision = '7ee26f6d76e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    # ### end Alembic commands ###
